[project]
name = "calulate-words-freaquency"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ChernovAO", email = "chernov.aleksandre@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
calulate-words-freaquency = "calulate_words_freaquency.calculate_words_freaquency:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
